# Batch CLI Configuration

# Basic configuration
format: openai  # Options: "openai" or "anthropic"
n_answers: 5    # Number of responses to generate per question

# Model configuration
model: gpt-4o-mini
temperature: 0.7
max_tokens: 8196 # Maximum number of tokens to generate, required by Anthropic

# System message - multiline format for complex prompts
# system_message: |
#   You are a helpful assistant. 
#   Answer questions clearly and concisely.
#   When code is requested, provide well-structured, type-hinted solutions.

# Optional parameters passed directly to the API
# kwargs:
#   top_p: 0.9
#   frequency_penalty: 0.0
#   presence_penalty: 0.0